import Head from "next/head";
import Image from "next/image";
import { useSelector } from "react-redux";

export default function Home() {
  const store = useSelector((state) => state);
  console.log("storestorestore", store);
  return (
    <div>
      <Head>
        <title>iSteps-test</title>
        <meta name="description" content="Generated by @AbdelrhmanGad with create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container main">
        <h1>Hello</h1>
      </main>

      <footer className="footer"></footer>
    </div>
  );
}
